WORLD_NEWS=["https://www.indiatoday.in/rss/1206577",
    "http://feeds.feedburner.com/ndtvnews-world-news?format=xml"
]

INDIA=["https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"]
US=["https://timesofindia.indiatimes.com/rssfeeds_us/72258322.cms"]
UK=["https://timesofindia.indiatimes.com/rssfeeds/2177298.cms"]
PAKISTAN=["https://timesofindia.indiatimes.com/rssfeeds/30359534.cms"]
CHINA=["https://timesofindia.indiatimes.com/rssfeeds/1898184.cms"]
EUROPE=["https://timesofindia.indiatimes.com/rssfeeds/1898274.cms"]


MUMBAI=["https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms"]
DELHI=["https://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms"]
BANGLORE=["https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms"]
HYDERABAD=["https://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms"]
CHENNAI=["https://timesofindia.indiatimes.com/rssfeeds/2950623.cms"]
AHEMDABHAD=["https://timesofindia.indiatimes.com/rssfeeds/-2128821153.cms"]
ALLAHABAD=["https://timesofindia.indiatimes.com/rssfeeds/3947060.cms"]
BHUBANESWAR=["https://timesofindia.indiatimes.com/rssfeeds/4118235.cms"]
COMIBATORE=["https://timesofindia.indiatimes.com/rssfeeds/7503091.cms"]
GURAGON=["https://timesofindia.indiatimes.com/rssfeeds/6547154.cms"]
GUWAHATI=["https://timesofindia.indiatimes.com/rssfeeds/4118215.cms"]
HUBLI=["https://timesofindia.indiatimes.com/rssfeeds/3942695.cms"]
KANPUR=["https://timesofindia.indiatimes.com/rssfeeds/3947067.cms"]
KOLKATA=["https://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms"]
LUDHIANA=["https://timesofindia.indiatimes.com/rssfeeds/3947051.cms"]
MANGALORE=["https://timesofindia.indiatimes.com/rssfeeds/3942690.cms"]
MYSORE=["https://timesofindia.indiatimes.com/rssfeeds/3942693.cms"]
NOIDA=["https://timesofindia.indiatimes.com/rssfeeds/8021716.cms"]
PUNE=["https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms"]
GOA=["https://timesofindia.indiatimes.com/rssfeeds/3012535.cms"]
CHANDIGARH=["https://timesofindia.indiatimes.com/rssfeeds/-2128816762.cms"]
LUCKNOW=["https://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms"]
PATNA=["https://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms"]
JAIPUR=["https://timesofindia.indiatimes.com/rssfeeds/3012544.cms"]
NAGPUR=["https://timesofindia.indiatimes.com/rssfeeds/442002.cms"]
RAJKOT=["https://timesofindia.indiatimes.com/rssfeeds/3942663.cms"]
RANCHI=["https://timesofindia.indiatimes.com/rssfeeds/4118245.cms"]
SURAT=["https://timesofindia.indiatimes.com/rssfeeds/3942660.cms"]
VADODARA=["https://timesofindia.indiatimes.com/rssfeeds/3942666.cms"]
VARANASI=["https://timesofindia.indiatimes.com/rssfeeds/3947071.cms"]
THANE=["https://timesofindia.indiatimes.com/rssfeeds/3831863.cms"]
THIRUVANANTHAPURAM=["https://timesofindia.indiatimes.com/rssfeeds/878156304.cms"]

ANDHRA_PRADESH=["https://www.thehindu.com/news/national/andhra-pradesh/feeder/default.rss"]
KARNATAKA=["https://www.thehindu.com/news/national/karnataka/feeder/default.rss"]
KERALA=["https://www.thehindu.com/news/national/kerala/feeder/default.rss"]
TAMIL_NADU=["https://www.thehindu.com/news/national/tamil-nadu/feeder/default.rss"]
TELANGANA=["https://www.thehindu.com/news/national/telangana/feeder/default.rss"]
OTHER_STATES=["https://www.thehindu.com/news/national/other-states/feeder/default.rss"]

