from top import TOP_NEWS
from locations import *
from business import BUSINESS
from mostread import MOST_READ
from education import EDUCATION
from entertainment import ENTERTAINMENT
from recent import MOST_RECENT
from science import SCIENCE
from sports import SPORTS
from tech import TECH

NEWS={
    "top":TOP_NEWS,
    "World":WORLD_NEWS,
    "India":INDIA,
    "US":US,
    "UK":UK,
    "China":CHINA,
    "Pakistan":PAKISTAN,
    "Europe":EUROPE,
    "Mumbai":MUMBAI,
    "Delhi":DELHI,
    "Banglore":BANGLORE,
    "Hyderabad":HYDERABAD,
    "Chennai":CHENNAI,
    "Ahemdabhad":AHEMDABHAD,
    "Allahabad":ALLAHABAD,
    "Bhubaneswar":BHUBANESWAR,
    "Coimbatore":COMIBATORE,
    "Guragon":GURAGON,
    "Guwahati":GUWAHATI,
    "Hubli":HUBLI,
    "Kanpur":KANPUR,
    "Kolkata":KOLKATA,
    "Ludhiana":LUDHIANA,
    "Mangalore":MANGALORE,
    "Mysore":MYSORE,
    "Noida":NOIDA,
    "Pune":PUNE,
    "Goa":GOA,
    "Chandigarh":CHANDIGARH,
    "Lucknow":LUCKNOW,
    "Patna":PATNA,
    "Jaipur":JAIPUR,
    "Nagpur":NAGPUR,
    "Rajkot":RAJKOT,
    "Ranchi":RANCHI,
    "Surat":SURAT,
    "Vadodara":VADODARA,
    "Varanasi":VARANASI,
    "Thane":THANE,
    "Thiruvananthapuram":THIRUVANANTHAPURAM,
    "Andhra Pradesh":ANDHRA_PRADESH,
    "Tamil Nadu":TAMIL_NADU,
    "Karnataka":KARNATAKA,
    "Telangana":TELANGANA,
    "Kerala":KERALA,
    "Arunachal Pradesh" : OTHER_STATES,
    "Assam" : OTHER_STATES,
    "Bihar" : OTHER_STATES,
    "Chhattisgarh" : OTHER_STATES,
    "Goa" : OTHER_STATES,
    "Gujarat" : OTHER_STATES,
    "Haryana" : OTHER_STATES,
    "Himachal Pradesh" : OTHER_STATES,
    "Jharkhand" : OTHER_STATES,
    "Madhya Pradesh" : OTHER_STATES,
    "Maharashtra" : OTHER_STATES,
    "Manipur" : OTHER_STATES,
    "Meghalaya" : OTHER_STATES,
    "Mizoram" : OTHER_STATES,
    "Nagaland" : OTHER_STATES,
    "Odisha" : OTHER_STATES,
    "Punjab" : OTHER_STATES,
    "Rajasthan" : OTHER_STATES,
    "Sikkim" : OTHER_STATES,
    "Tripura" : OTHER_STATES,
    "Uttarakhand" : OTHER_STATES,
    "Uttar Pradesh" : OTHER_STATES,
    "West Bengal" : OTHER_STATES,
    "business":BUSINESS,
    "most-read":MOST_READ,
    "education":EDUCATION,
    "entertainment":ENTERTAINMENT,
    "most-recent":MOST_RECENT,
    "science":SCIENCE,
    "sports":SPORTS,
    "tech":TECH
}